inicio tradução como javascript funciona
entrylvl/traducoes-de-artigos pull request #21
Opened 2017-10-03 21:49 UTC by Siqs

- falta traduzir quatro tópicos
- encontrar palavras melhores para single-threaded e callback
- formatar o texto

2017-10-04 19:16 UTC, BikeCoding commented
Olá @Siqs vou te ajudar na tradução ok? Vou começar pelo próximo tópico =)

2017-10-04 22:46 UTC, devplusti commented
Gostaria de ajudar formatando. O que devo fazer?

2017-10-06 02:15 UTC, Siqs commented
Opa @devplusti, desculpa, não tinha visto a mensagem antes! A @BikeCoding já deu uma formatada quando traduziu uma parte nova, mas se quiser dar uma olhada no arquivo (está dentro da pasta javascript) e quiser dar uma formatada com o markdown do GitHub, sinta-se à vontade!

2017-10-07 14:19 UTC, felipesoares6 reviewed
@Siqs estou traduzindo a seção The Runtime

2017-10-07 14:52 UTC, CarolPC reviewed
@Siqs estou traduzindo a seção `The Call Stack`

2017-10-23 22:34 UTC, KaiqueMunhoz commented
Gostaria de colaborar com o tópico: "Concurrency & the Event Loop"

2018-02-20 02:51 UTC, felipesoares6 requested changes

2018-02-20 02:51 UTC, felipesoares6 commented on README.md
>  * [Javascript para gatos](javascript/javascript-para-gatos.md)
JavaScript

2018-02-20 02:51 UTC, felipesoares6 commented on javascript/como-javascript-funciona.md
> +### Como Javascript funciona: uma visão geral da engine, do runtime e da pilha de chamadas
JavaScript

2018-02-20 02:51 UTC, felipesoares6 commented on javascript/como-javascript-funciona.md
> +O que acontece quando você tem chamadas de função na Pilha de Chamadas que leva uma grande quantidade de tempo para ser processada? Por exemplo, imagine que você quer fazer alguma transformação de im
JavaScript

2018-02-20 02:51 UTC, felipesoares6 commented on javascript/como-javascript-funciona.md
> +Isso será explicado com mais detalhes na **Parte 2** de "Como Javascript realmente funciona" tutorial: ["Dentro da engine v8 + 5 dicas de como escrever códigos otimizados"](https://blog.sessionstack.
JavaScript

2018-02-20 02:51 UTC, felipesoares6 commented on javascript/como-javascript-funciona.md
> +Nesse meio tempo, se você está tendo um tempo difícil, reproduzindo e entendendo problemas nos seus apps Javascript, de uma olhada em [`SessionStack`](https://www.sessionstack.com/). `SessionStack` g
JavaScript antes de `apps` & depois de `exceções`

2018-02-20 03:12 UTC, feliperli requested changes

2018-02-20 03:12 UTC, feliperli commented on javascript/como-javascript-funciona.md
> +####Confira as estatísticas de língua atualizadas
Coloque um espaço entre #### e Confira pros mesmos n serem visíveis

2018-02-20 03:25 UTC, feliperli requested changes

2018-02-20 03:25 UTC, feliperli commented on javascript/como-javascript-funciona.md
> +Como JavaScript está ficando cada vez mais popular, times tem se aproveitado de seu suporte para vários papéis em suas funções - front-ned, back-end, aplicativos hibridos e muito mais.
*front-end, híbridos tem acento e, por fim, acho que seria legal colocar trocar o primeiro - por :, por exemplo: "... papéis em suas funções : front-ned, back-end, aplicativos híbridos e muito mais."

2018-02-20 03:25 UTC, feliperli commented on javascript/como-javascript-funciona.md
> +Este post é o primeiro numa série com a intenção de se aprofundar em JavaScript e em como ele realmente funciona: nos achamos que ao saber como os blocos de construçāo do JavaScript e como eles se in
acento agudo no nós em "nos achamos que ao saber..."

2018-02-20 03:25 UTC, feliperli commented on javascript/como-javascript-funciona.md
> +A pilha de chamadas é uma estrutura de dados que salva basicamente onde estamos no programa. Se entrarmos em uma função, nos a colocamos no topo da pilha. Se saírmos de uma função, nós tiramos ela do
Colocar acento agudo no nós em "Se entrarmos em uma função, nós a colocamos..."

2020-09-08 23:34 UTC, closed without merging