[Artigo] How I Start: Elixir
entrylvl/traducoes-de-artigos pull request #48
Opened 2017-10-30 14:29 UTC by rhiroyuki

#21

Tradução sendo realizada junto com o @caiquemitsuoka

2018-02-20 02:35 UTC, felipesoares6 commented
@CaiqueMitsuoka @rhiroyuki @JulioFortunato como está esse artigo, pretendem continuar a tradução?

2018-05-14 17:56 UTC, juunegreiros commented
Eai @CaiqueMitsuoka e @rhiroyuki, beleza? Como está o andamento dessa tradução? Consigo ajudar a traduzir?

2018-05-16 17:41 UTC, rhiroyuki commented
Olá @juunegreiros, pode sim. Falta pouca coisa. Vou mandar o artigo original para você dar uma lida.
http://howistart.org/posts/elixir/1/

Você pode traduzir as partes em que está escrito 'Caique'.

Obrigado pela ajuda :)

2018-05-17 22:12 UTC, rhiroyuki commented on elixir/como-comecar.md
> +  Inicia uma dor com a `cor` recebida.
No `dor` era pra ser `acesso`?

2018-05-18 02:02 UTC, juunegreiros commented on elixir/como-comecar.md
> +  Inicia uma dor com a `cor` recebida.
Era! Porque que eu coloquei dor eu não sei não uahauhauha Arrumarei

2018-05-18 14:37 UTC, juliofortunato requested changes

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +Vamos explorar o projeto gerado usando um editor de texto. Eu pessoalmente não presto muita atenção em editores de texto, normalmente uso o [Sublime Text 3](http://www.sublimetext.com/3) mas você pod
Achei essa parte um pouco confusa.
O que acham de mudar:

> você pode achar suporte Elixir para diferentes editores de texto no site na sessão "Code Editor Support"

para:

> "você pode encontrar diferentes editores de texto com suporte ao Elixir no site na sessão "Code Editor Support"

?

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +Antes de implementarmos nosso aplicativo, precisamos falar sobre pattern matching. O operador = no Elixir é um pouco diferente do que vemos em outros idiomas:
Aqui eu trocaria `idiomas` por `linguagens`, para se adequar melhor ao contexto de desenvolvimento de software

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +As estruturas de data do Elixir são imutáveis. Nos exemplos acima, nós nunca mudamos a lista. Nós podemos quebrar em uma lista à parte ou adicionar novos elementos na cabeça, mas a lista original nun
"As estruturas de **dados** do Elixir [...]"

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +  Returna `{:ok, valor}` se existe um valor
**Retorna** {:ok, valor} [...]

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +iex(3)> portal = Portal.transfere(:laranja, :azul, [1, 2, 3, 4])
Aqui estamos dando nomes em português para as funções como `Portal.trasfere()`, `Portal.atirar()` e `Portal.inserir_direita()`, mas nos exemplos de código ao longo do artigo, estão sendo implementada em inglês.

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +  # First add all data to the portal on the left
Como nos outros trechos de código os comentários foram traduzidos, eu sugiro manter esse padrão e traduzir aqui também.

2018-05-18 14:37 UTC, juliofortunato commented on elixir/como-comecar.md
> +Nós recebemos uma mensagem de erro porque a porta `:azul` não existe. Você pode ver a mensagem `** (EXIT) no process` depois da nossa chamada da função. Para concertar a situação, nós vamos configura
"concertar"  -> **consertar**

2018-05-18 19:01 UTC, juliofortunato approved these changes

2018-05-18 20:48 UTC, felipesoares6 requested changes

2018-05-18 20:48 UTC, felipesoares6 commented on elixir/como-comecar.md
> +* Adicione uma funcão `Portal.push_left/1` que transfira os dados na outra direção. Como você pode evitar o código duplicado existente entre as funções `push_left/1` e `push_right/1`?
função *

2018-05-18 20:48 UTC, felipesoares6 commented on elixir/como-comecar.md
> +Nós convidamos você para explorar nosso [site](http://elixir-lang.org/) e ler nosso guia Getting Started ou outros dos muitos recursos disponíveis para aprender mas sobre Elixir e nossa comunidade vi
aprender mais*

2018-05-21 14:06 UTC, felipesoares6 requested changes

2018-05-21 14:06 UTC, felipesoares6 commented on elixir/como-comecar.md
> +m
:fire:

2018-05-21 14:14 UTC, felipesoares6 commented
@juunegreiros Poderia adicionar ao readme o novo tópico Elixir e listar esse artigo lá? :smile:

2018-05-21 16:35 UTC, felipesoares6 approved these changes

2018-05-28 20:39 UTC, merged