Add introduction and table of content
entrylvl/traducoes-de-artigos pull request #5
Opened 2017-09-18 17:06 UTC by CarolPC

Link para o artigo original: https://github.com/maxogden/javascript-for-cats

2017-09-18 17:59 UTC, JulioFortunato commented
Traduzindo seção "**Objects**"

2017-09-19 01:14 UTC, feliperli commented
Traduzindo seção "Strings"

2017-09-19 01:24 UTC, feliperli commented
Traduzindo a seção **Values and Variables**

2017-09-19 13:22 UTC, JulioFortunato commented
Traduzindo seção "**Arrays**"

2017-09-19 18:07 UTC, JulioFortunato commented
Traduzindo seção "**Loops**"

2017-09-21 13:58 UTC, JulioFortunato commented
Traduzindo seção **Making new functions**

2017-09-21 16:37 UTC, feliperli commented
Traduzindo seção **Using Functions**

2017-09-21 18:11 UTC, feliperli commented
Traduzindo the standart library

2017-09-22 12:35 UTC, JulioFortunato commented
Traduzindo seção **Callbacks**

2017-09-22 16:43 UTC, feliperli commented
Traduzindo seção **Third Party Javascript**

2017-09-22 17:10 UTC, feliperli commented
Traduzindo seção **Recomended Reading**

2017-09-23 14:16 UTC, felipesoares6 requested changes

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +JavaScript é uma lingugagem de programação ou, em outras palavras, uma maneira pela qual o computador é instruído a fazer coisas. Da mesma forma que um controla humanos com assobios e miados, um pode
`Da mesma forma que um controla humanos com assobios e miados` `Just the same as one controls humans with hisses and meows` Tanto no original quanto aqui parecer faltar explicitar quem é o sujeito 🤔  Talvez podemos colocar `Da mesma forma que um felino controla humaos` deixando o sujeito explicito.

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +JavaScript começou como uma forma de tornar as páginas `web` mais interativas. Hoje em dia JavaScript roda em muitos lugares além dos `web browsers` - roda em servidores `web`, celulares e até robôs!
No nosso caso não é uma página e sim um artigo, talvez valesse a pena trocar para `Esse artigo`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Isso é um console, também conhecido como "linha de comando" ou "terminal". Basicamente é um jeito de digitar uma coisa por vez em um computador, e imediatamente receber a resposta do computador de vo
`ferramente` para `ferramenta`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +O console faz umas coisas muito legais. Aqui eu comecei a digitar uma coisa e o console está me ajudando dando a lista de todas as coisas que eu poderia continuar digitando. Outra coisa que você pode
dois espaços depois do `pressionar`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Já que eu sou um gato, eu quero trocar cada instância da palavra `cachorro` na internet com `esses cachorros malditos`. Primeiro, vá no seu console e digite algumas frases que contenham a palavra `ca
Não tenho certeza, mas acho que seria `usando as mesmas aspas` ao invés de `usando a mesma aspas`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +**Valores** são os componentes mais simples no JavaScript. `1` é um valor, `true` é um valor, `"olá"` é um valor, `function() {}`é um valor, a lista pode continuar! Tem um monte de **tipos** diferent
Acredito que o correto seja `aprendê-los`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +`var`é a abreviatura de variável e o `=`significa *guarde esta coisa do lado direito na coisa do lado esquerdo*. Além disso, como você pode ver, agora que estamos guardando a nossa sentença nessa var
faltou um espaço depois do `=`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Agora que temos a nossa sentença armazenada em uma variável, vamos trocar a palavra que está dentro dela! Nós podemos fazer isso realizando uma *função*. *Funções* são um tipo de valor que, bem, serv
`Chamar elas de "ações"` acho que fica mais fluido

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +JavaScript tem uma função chamada `replace`que faz exatamente o que nós queremos! Funções pegam qualquer número de valores em seus parenteses (zero, um ou muitos) e retorna ou `undefined` (nada) ou a
faltou um espaço dps do `replace`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +JavaScript tem uma função chamada `replace`que faz exatamente o que nós queremos! Funções pegam qualquer número de valores em seus parenteses (zero, um ou muitos) e retorna ou `undefined` (nada) ou a
o correto é `parênteses`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Você deve estar imaginando quais outras funções estão disponíveis no JavaScript. A resposta: UMA TONELADA. Existem muitas **bibliotecas embutidas** que você pode aprender sobre no MDN (um site admini
`pela Mozzila` é uma org

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Existe também muito código de JavaScript que não é **embutido**. O código externo de JavaScript é geralmente referido como "biblioteca" ou "plugin". Um dos meus favoritos é chamado **Underscore.js**.
o correto é `Vamos lá usá-lo e carregá-lo`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Existe também muito código de JavaScript que não é **embutido**. O código externo de JavaScript é geralmente referido como "biblioteca" ou "plugin". Um dos meus favoritos é chamado **Underscore.js**.
tem outro  `usa-lo` no final do parágrafo, trocar por `usá-lo`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +A última linha da função é outro método nativo que simplesmente recebe quaisquer valores e, então, exibe-os no console.
O correto parece ser `exíbe-os`

2017-09-23 14:16 UTC, felipesoares6 commented on javascript-para-gatos.md
> +Se nós escrevessemos manualmente o que `times` está fazendo no código acima, ele seria parecido com isto:
o correto é `escrevêssemos`

2017-09-23 16:54 UTC, feliperli commented
Corrigindo o artigo de acordo com as observações do @felipesoares6

2017-09-25 18:30 UTC, felipesoares6 approved these changes

2017-09-25 19:06 UTC, CarolPC commented on javascript-para-gatos.md
> +OK, pra consertar essas sentenças (substituindo `cachorro` com a nossa versão melhorada) nós precisamos primeiro salvar a sentença original para que possamos chama-la mais tarde com a nossa magia de
Aqui deveria ser `chamá-la`

2017-09-25 19:06 UTC, CarolPC commented on javascript-para-gatos.md
> +OK, pra consertar essas sentenças (substituindo `cachorro` com a nossa versão melhorada) nós precisamos primeiro salvar a sentença original para que possamos chama-la mais tarde com a nossa magia de
E `Percebe como a string...`

2017-09-25 19:06 UTC, CarolPC commented on javascript-para-gatos.md
> +Você deve estar imaginando quais outras funções estão disponíveis no JavaScript. A resposta: UMA TONELADA. Existem muitas **bibliotecas embutidas** que você pode aprender sobre no MDN (um site admini
Ficou errado aqui como o link foi adicionado.

2017-09-25 19:41 UTC, merged