Adiciona tradução do artigo "Como começar na área de UX"
entrylvl/traducoes-de-artigos pull request #54
Opened 2018-02-01 00:58 UTC by amandavilela

2018-02-06 19:54 UTC, juliofortunato requested changes

2018-02-06 19:54 UTC, JulioFortunato commented on ux/como-comecar-na-area-de-ux
> +A tecnologia se integrou em nossas vidas de várias maneiras - na maneira como interagimos, na maneira como fazemos conexões / relacionamentos, nossa base de comunicação, entretenimento (exceto qualqu
Eu trocaria `em uma tarde de outono frio` por "eu uma tarde fria de outono", mas isso é só 💅

2018-02-06 19:54 UTC, JulioFortunato commented on ux/como-comecar-na-area-de-ux
> +Uma coisa que ainda falta na aprendizagem online para mim, é a instrução e crítica de que se pode aprender no contexto de outros alunos. O professor não apenas dá uma palestra de sentido único e espe
"`Uma simples explicação de um colega de classe para pode conciliar um conceito difícil`". 

Acho que esse `para` está sobrando aí

2018-02-18 17:07 UTC, merged

2018-02-18 17:07 UTC, felipebernardes commented
GJ @amandavilela  obrigado pela contribuição! nas próximas semanas iremos lançar o blog do entrylvl e sua tradução estará lá!